### ISSUE TITLE
Is it possible to have documentation written in English?

### ISSUE THREAD

**Issue by kenshinji** [BcRikko/NES.css#1]
That would be great, thanks. I wish I could help on it, however I only know English and Chinese.

**Comment by BcRikko** [comment]
Thanks 👍 

I know English a little bit, while I don't know Chinese.
Please give me some time to write document in English.

**Comment by BcRikko** [comment]
Yeah! 😆 
When the English document  is finished, I will create a translation issue. then cloud you help me translate into Chinese?

**Comment by kenshinji** [comment]
sure thing, dude :) @BcRikko

**Comment by BcRikko** [comment]
hi @kenshinji 👋 

We created English document 📝 
Could you translate `README.md` into Chinese if you dont't mind? 😆

refs
* https://github.com/nostalgic-css/NES.css/pull/145
* https://github.com/nostalgic-css/NES.css/pull/138

**Comment by kenshinji** [comment]
@BcRikko I noticed you mentioned me in this issue about help wanted for Chinese translation, so I created this PR https://github.com/nostalgic-css/NES.css/pull/186.

**Comment by BcRikko** [comment]
@kenshinji Thanks, I'm so happy😍 

but Sorry to trouble you...
I sent you information that was incorrect. 🙇
