### ISSUE TITLE
Primary and success button colors reversed?

### ISSUE THREAD

**Issue by mlterpstra-umc** [BcRikko/NES.css#19]
On the NES.css github.io page success and primary buttons look like this: 
![2018-11-29-094947_324x70_scrot](https://user-images.githubusercontent.com/43781235/49210030-51686f00-f3bc-11e8-97c3-781e1bc5c2c3.png)

In Bootstrap they look like this:
![2018-11-29-095034_187x64_scrot](https://user-images.githubusercontent.com/43781235/49210068-6a712000-f3bc-11e8-858d-cbef5601d131.png)

As you can see the colors are swapped. Is this intended? It would would make more sense to me if the success color is green and the primary color is blue, like Bootstrap.

**Comment by BcRikko** [comment]
Thanks.

It's a good point 👍 
I didn't notice 😇 

I'll fix this issue.

**Comment by KeevanDance** [comment]
I'll try and fix this if it hasn't been done yet!

**Comment by BcRikko** [comment]
@KeevanDance I have not started this issue yet.
I would be happy if you could do that. 😆🎉

**Comment by KeevanDance** [comment]
@BcRikko Already submitted a pull request :)
