### ISSUE TITLE
Gnerated CSS from Pixelize adds double semi-colon instead of one

### ISSUE THREAD

**Issue by abouroubi** [BcRikko/NES.css#21]
https://github.com/BcRikko/NES.css/blob/2374bef951c2a6359dcd2041d2bdb123ce396e31/css/nes.css#L604

Please check the end of the line.
In my opinion the mixin already ends the line with ; so ne need to add another when you call the mixin.

I could do a PR if needed :)

**Comment by BcRikko** [comment]
Oh, I didn't notice...
It's greate issue 👍 

Is the problem code below?
https://github.com/BcRikko/NES.css/blob/2374bef951c2a6359dcd2041d2bdb123ce396e31/scss/utilities/icon-mixin.scss#L23

Please pull request 🙏 😆

**Comment by abouroubi** [comment]
Yes it was this one line.

PR created.
