### ISSUE TITLE
Button elements have no keyboard focus style

### ISSUE THREAD

**Issue by scottaohara** [BcRikko/NES.css#22]
When navigating through the test page by use of the <kbd>Tab</kbd> key, that there were no `:focus` styles for the `button` examples due to their focus outline being set to zero.

Whenever removing native focus styles from interactive controls, custom focus styles should be put in place so as to not create an inaccessible experience for those who do not navigate by mouse.

**Comment by BcRikko** [comment]
Thansk for PR too. 🙇

**Comment by BcRikko** [comment]
Is it OK to merge this PR? 🤔 
#24 was merges.

**Comment by BcRikko** [comment]
#24 was merged.
