### ISSUE TITLE
Demo site should associate labels with text inputs

### ISSUE THREAD

**Issue by scottaohara** [BcRikko/NES.css#28]
As discussed in #24, `id`s are not necessary to associate `label`s with their form controls, as long as those form controls are contained within the `label`.  However, if a `label` is not a parent for its form control, then the `label` should have a `for` attribute, pointing to the unique `id` of the element it is providing the accessible name to.

The text fields on the demo site would fall into this pattern.

**Comment by BcRikko** [comment]
Does this mean? ↓  🤔 

### Unnecessary

```html
<label>
  Input field
  <input type="text" class="input">
</label>
```

### Necessary

```html
<label for="input_field">Input field</label>
<input type="text" class="input" id="input_field">
```


That's right, I did not know. 😆 

Do you know best practices for not duplicating IDs?
Would you teach me for my future? 🙏

**Comment by scottaohara** [comment]
We can have a side conversation sometime about this, yes
