### ISSUE TITLE
Inconsistent base pixel size

### ISSUE THREAD

**Issue by zreese** [BcRikko/NES.css#33]
The NES did not support scaling, so the size of "one pixel" should be the same for every element. Currently this isn't the case for checkboxes and icons. Checkboxes are smaller than the single pixel used by fonts and borders, and the icons scale.

**Comment by BcRikko** [comment]
Thanks 🙇 

I create pixel art with `box-shadow`. so unsupported scaling. 
Do I have to make them↓ all the same size?(2px or 4px) 🤔 

https://github.com/BcRikko/NES.css/blob/4c6bf1f8883a39e3eb3bc368ecbce3257ec99b7d/scss/elements/checkboxes.scss#L69-L70

https://github.com/BcRikko/NES.css/blob/4c6bf1f8883a39e3eb3bc368ecbce3257ec99b7d/scss/elements/radios.scss#L50-L52

https://github.com/BcRikko/NES.css/blob/4c6bf1f8883a39e3eb3bc368ecbce3257ec99b7d/scss/elements/buttons.scss#L18-L19

https://github.com/BcRikko/NES.css/blob/4c6bf1f8883a39e3eb3bc368ecbce3257ec99b7d/scss/elements/containers.scss#L30

It may be difficult to fix. 😢

**Comment by BcRikko** [comment]
I'll close it 🙇
if you need to reopen, please let me know. 🙏
