### ISSUE TITLE
[Feature request] Change Table design

### ISSUE THREAD

**Issue by guastallaigor** [BcRikko/NES.css#35]
Not sure if this is a good feature request, but I notice that on the `<table>` tag, you only changed the border-collapse CSS property, and did nothing else. 

Maybe change the table design similar to the container, but with the possibility to also have borders. Could be a CSS class added to the table like `is-bordered` or something like that, and maybe some other things.

**Example:**
![123](https://user-images.githubusercontent.com/22016005/49250630-6f5ac180-f406-11e8-823b-63a1da11e11d.png)

If you think it's a good idea I can try do this. Great job on building this project 👍

**Comment by BcRikko** [comment]
It's great idea 😍
