### ISSUE TITLE
accentued characters are not supported by fonts

### ISSUE THREAD

**Issue by tuxun** [BcRikko/NES.css#37]
Hi, i'm french, we sometimes use somes É È Ô Ù À (and same in lowercase: é à è ô ê etc) key on our keyboard, also know as [latin-1 or iso8859 charset](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) 

Sadly the font doesn't seems handle them and show `�`.
Its present on unicode under https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block), i was wondering, is there a chance that someone comes here and add these characters to the font?

We need the right to do it (modify the font), and some fontforge use (a opensource software able to do it) I guess, but i'm bad designer :/

**Comment by trezy** [comment]
@BcRikko Between this issue and #34, it'd be great if we could get a section in the README for "Recommended Fonts." [Kongtext](https://www.dafont.com/kongtext.font) is the only other pixel font I can think of at the moment that may fit with the framework, but as users find other fonts that work well — for example, if you have a 16-bit font you use for Japanese already — they can make pull requests to add them to the list.

**Comment by BcRikko** [comment]
It's greate idea 🎉 

Is it like below? 😆 

## Recommended Fonts

|Lang|Font|
|---|---|
|(Default)|[Press Start 2P](https://fonts.google.com/specimen/Press+Start+2P)|
|English|[Kongtext](https://www.dafont.com/kongtext.font)|
|Japanese|[美咲フォント](http://www.geocities.jp/littlimi/misaki.htm)|
