### ISSUE TITLE
The logo icon is not a NES controller, but SNES

### ISSUE THREAD

**Issue by megane42** [BcRikko/NES.css#5]
## Expected behavior

![image](https://user-images.githubusercontent.com/8451003/49069216-09d2cd80-f26c-11e8-87af-39aae62d06b2.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/8451003/49069193-f889c100-f26b-11e8-8f62-161aa0028b28.png)

**Comment by BcRikko** [comment]
You're right 🙆 

It's a joke framework.
So, it might not be accurate.

Please have fun and use it 👍

**Comment by megane42** [comment]
OK, I understand. Close this issue if you want.
Thank you for very impressive framework <3<3

**Comment by BcRikko** [comment]
I'll try making **Exact** NES Controller. 🎮 
I close it when It's finished. 👍
