### ISSUE TITLE
Input success is incorrect

### ISSUE THREAD

**Issue by KeevanDance** [BcRikko/NES.css#51]
Input success should be the green success color, not blue. Semi-related to #19

**Comment by KeevanDance** [comment]
I'll go ahead and submit a pull request for this one!

**Comment by BcRikko** [comment]
#52

**Comment by BcRikko** [comment]
Sorry, I made a mistake 😱 
I reopened it. 🙇

**Comment by KeevanDance** [comment]
@BcRikko Should be good!

**Comment by BcRikko** [comment]
I merged #56 🙏
