### ISSUE TITLE
Feature request : Icons empty state

### ISSUE THREAD

**Issue by guidouil** [BcRikko/NES.css#53]
Hello @BcRikko,
Can you please add a parameter to make the heart ❤️and / or star ⭐️empty / transparent inside ?
Like a "is-empty" class to the icon.
Using your "Reaction" design, I want to make a ratting interface.
I believe it's only adding some color code in the scss but I'm don't know how to do it 😭

Anyway, thank you very much for your work 👍

**Comment by BcRikko** [comment]
It's good 👍

**Comment by BcRikko** [comment]
@guidouil  What do you think of this? 🤔 
![2018-12-02 12 10 51](https://user-images.githubusercontent.com/5305599/49335162-7f071f80-f62b-11e8-8b93-54c4301ee43a.png)

**Comment by guidouil** [comment]
I like it very much :)
Does it also work with `is-medium` and `is-large` (like a large empty star) ?

**Comment by BcRikko** [comment]
Yes, of course 👍
