### ISSUE TITLE
Bug with checkbox color?

### ISSUE THREAD

**Issue by KeevanDance** [BcRikko/NES.css#70]
Seems while clicking the checkbox multiple times, the shade of the box changes inconsistently.

Darker Checked:
![image](https://user-images.githubusercontent.com/10778294/49420569-b66fec00-f751-11e8-9acf-310cae28962b.png)

Lighter Checked:
![image](https://user-images.githubusercontent.com/10778294/49420582-c4257180-f751-11e8-9d2a-29c6a1ec7a94.png)

Lighter Empty:
![image](https://user-images.githubusercontent.com/10778294/49420595-d3a4ba80-f751-11e8-8b53-4ed8891003af.png)

Darker Empty:
![image](https://user-images.githubusercontent.com/10778294/49420610-ea4b1180-f751-11e8-8738-2eb03b724025.png)

I think it may be related to clicking the label vs clicking the checkbox itself.

**Comment by BcRikko** [comment]
It's a no problem. 🙆 
The color will change light gray when focus. 👍 

https://github.com/BcRikko/NES.css/blob/1663f704c194818460ad4b2cf7d0cb1e8c25f868/scss/elements/checkboxes.scss#L69-L82

**Comment by KeevanDance** [comment]
oh totally my mistake! The different states were confusing me so much, but that all makes sense! I will close it. Thanks for the quick reply @BcRikko  👍

**Comment by BcRikko** [comment]
Thanks for closing issue. 😆
