### ISSUE TITLE
disabled button state

### ISSUE THREAD

**Issue by mreinstein** [BcRikko/NES.css#83]
It would be great if disabled buttons rendered slightly differently (perhaps more grey-ed out?)

**Comment by BcRikko** [comment]
Thanks 👍 
great idea 🎉

**Comment by guastallaigor** [comment]
What do you guys think of this?

![image](https://user-images.githubusercontent.com/22016005/49552592-6b81e000-f8db-11e8-96b7-2290d17931e3.png)

The icon at the middle it's the `cursor: not-allowed` property.

**Comment by mreinstein** [comment]
that looks awesome!
