### ISSUE TITLE
Should remove the input outline

### ISSUE THREAD

**Issue by djyde** [BcRikko/NES.css#9]
Should remove the input outline. 

Before:

![image](https://user-images.githubusercontent.com/914329/49128327-d3499100-f305-11e8-9716-b82eb12e0dd4.png)

After:

![image](https://user-images.githubusercontent.com/914329/49128338-e4929d80-f305-11e8-805a-a34ad4dd2e0e.png)

**Comment by BcRikko** [comment]
Thanks.

I'll fix it 🔧

**Comment by djyde** [comment]
Maybe just change the outline color

**Comment by BcRikko** [comment]
Oh, I see 👍 

How about this?
![outline](https://user-images.githubusercontent.com/5305599/49134369-a5c10f80-f326-11e8-94ae-385dc7b98d10.gif)

**Comment by djyde** [comment]
@BcRikko Look good!
